[[z3]]
arch = "aarch64"
git-tree-sha1 = "88b8fb82fdf066e72397a432c0f9371ea76193b7"
julia_version = "1.10.0"
os = "macos"

    [[z3.download]]
    sha256 = "a2f6a15482635058e50ad270b4103403c7419f02a808c7ac8ecbf219d43c613e"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "aarch64"
git-tree-sha1 = "ec1c1f21fc61c262298022dc2f021dc1037793f9"
julia_version = "1.11.1"
os = "macos"

    [[z3.download]]
    sha256 = "a22e201addcc054484c5ce02dccaeaee21a1763daa285260409d02e67709f1d2"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "aarch64"
git-tree-sha1 = "8d5850cf9ea504d8e32e06746aaaad6a26347476"
julia_version = "1.12.0"
os = "macos"

    [[z3.download]]
    sha256 = "afea2d71460b7b2debdb451ba7eae2342ffa0ec0e5a7c59988ca4cd49391bce6"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "aarch64"
git-tree-sha1 = "9dfaa456a6e9c49d9485704bc5bae5ac93f14489"
julia_version = "1.13.0"
os = "macos"

    [[z3.download]]
    sha256 = "5bf541868b6c81d828b602a68685fe39e408789ff2745f16afb69b4176b8e4eb"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7b93fa5cf23f49f7df8639ecabb4865b2827e58"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "7bc1e41423daa026960ad8247f22919f0d7b36223ec86409e2a82ed2d8e170c9"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "641657511f989520d85c351b07d83dcad724b0e5"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "d31e5eaf2ca0ae4def6afaa576dfe359f1a01825ee9ac84db73fa321cfc2cd5d"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e87846a25683373cc207196d0d1d7730fb36ae1"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "764b95f9609df416599ed224eb70be5ca340b16ba761954e57a744dbb3ab84f2"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "080c11e94ef696c9a130f5e45d0b3958c62c59ef"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "6091c54e450e6de0b1f8f9daecf051912eb7a644b8b4c78cfa17088a775b7b0c"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d45b9e02226bc3d30b75bc4ac0c8e5092102f80"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[z3.download]]
    sha256 = "3fc083978e7052d73cf8ce04873adf058b0c6af13c9ebc65aa520b4606a13c01"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-linux-musl-cxx11-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dae8b19ae004a0c5dd963462d9d9131e56006d9"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[z3.download]]
    sha256 = "fe0029b62ca41cf3c7b1ec833618051dd6647cb85e54cac3a6dce10eb75342b0"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81533771e28778bcfb5bb344da4ac446357e0315"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[z3.download]]
    sha256 = "d44fd13559544b1884f7fe2dcfc228464b29d54c5fbe8117c7bf57ea1a9bca47"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74011194fb5a5d8b08a37a4079e6aa4b082cb758"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[z3.download]]
    sha256 = "24c78ba7584e76824ae21368916e9a51bc829fe26dd7ad1cecd1560bc5e57bcc"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-linux-musl-cxx11-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "aarch64"
git-tree-sha1 = "d8ddc5b96b5017b1932022d500b359b197dd97f1"
julia_version = "1.12.0"
os = "freebsd"

    [[z3.download]]
    sha256 = "09dc370897ee9f824132fd37482477b4fc6099bae979ce60ae082f0de899f125"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "aarch64"
git-tree-sha1 = "70278e59e8a22eabcaebc44b7f1f2baf5bde284a"
julia_version = "1.13.0"
os = "freebsd"

    [[z3.download]]
    sha256 = "aa1db39dc1cc040aee9371316b8d2ddbcc117ca61f9baa9f8def2c614684b9c8"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.aarch64-unknown-freebsd-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c85eecd87ba1b4d57bf70327a78a87ff8070b826"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "3976e3e4aa7ef50dc0d9820f9f7552d0562be269ce0ba08091fd9e57a621d49c"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e558d54a738ae5d118e34b5a640c8613576492fe"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "cc86dd313a714fc7825f55675c28d213710f11782a72d4c7573cbe164bdffbab"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.i686-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "477c5b8404921453875d5448dda1882e4b25e0ca"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "778d8d944458f42982c80d63395ebd607b1e3cec76f8d3fc970fe7e9b9af297f"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fe80d0f58507efe1b5fa18a0db4364da9536609"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "d82a2e4ef64acfb0afb6065844cbbbeb1ea4a0b04df438173f4bae9babbbf236"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.i686-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59c5965ddc830788c6a95d2b332566e480ba6a2f"
julia_version = "1.10.0"
os = "windows"

    [[z3.download]]
    sha256 = "69d24a53ef1d3731274117ff27bcd5f36abd8ad319af5900a742d5b14e8bfd63"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.i686-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4072dcef6d8f4ad3b6a18099a0216d4a8288b4c4"
julia_version = "1.11.1"
os = "windows"

    [[z3.download]]
    sha256 = "555592031cdaaa8d1194eac50b5f707fd82c7e62140220900800ec73c4b3ba4e"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.i686-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9226a39738677439510b9a05aef565dc65f340cd"
julia_version = "1.12.0"
os = "windows"

    [[z3.download]]
    sha256 = "097335f36c5db3beb453db7a296279276352a9253c40f6ec24aa9602ef338187"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.i686-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efcf82ed60d74b1a04ecfbad6493ffcac015ae75"
julia_version = "1.13.0"
os = "windows"

    [[z3.download]]
    sha256 = "eb553ce4ef9f60c88b9f34ff5d6d2fe196fd1f0ac8fcf0cb3847187fafa6ba68"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.i686-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ff773f30a79538cc19b3e4eea36ae186acb0987"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "11d568b9430f3ab78cf1e99380e059f4ec38ab010f90b73b5e01fee9455e4c57"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5155aa8fda16b6d4f2489eff51746722c7e54135"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "bc04f8efdeec0dd2c23326dd82cfffbbb3753e582e67dcadafe0aab14da8f694"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "762b5b5c36233774c8cae5cdb1e9e387b6d2fe31"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "a23241b9a8854a6ed3db80655a2517d0e4b189bfacb9467afeb3205e88932dd4"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b73c34d7480495af9636a97fd2a6d9bb051fc7af"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "538e2377c7d400331c3249e3972c251dcb51d76cc67c6f24ca3e56240527d1e3"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.powerpc64le-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39f40fdce7301ce432ccf004ca69d4129eb7b596"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "e476b8ab093f2de3927b317e1297b649a2d2ff75bb6548a441e07d69d2543ad4"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.riscv64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "x86_64"
git-tree-sha1 = "40b8e4125e7c93aaf02dbd67d0880fc71db2fc3f"
julia_version = "1.10.0"
os = "macos"

    [[z3.download]]
    sha256 = "ba1f4c758be55b23d0cd8de4bbfab5dcdf5ee29a4431ae979ab8ba3e00988414"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "x86_64"
git-tree-sha1 = "8e18da1aa1778fc81a1272dfb1099dc7b0faa1d7"
julia_version = "1.11.1"
os = "macos"

    [[z3.download]]
    sha256 = "a82e0d47b2ef9ab4d8fcbaa54c8ecf3f42998a15644f7eb2ffed2fe898aad85d"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "x86_64"
git-tree-sha1 = "0af4277d856c58bd00ebb97c620c88e2139a5ced"
julia_version = "1.12.0"
os = "macos"

    [[z3.download]]
    sha256 = "3397e7e8f0f4b77cf4083b0ef00576491bb9afe58ad5fa2b185115af28a68d0f"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "x86_64"
git-tree-sha1 = "7cd91e46b6028a3a11247b678948c28b9e3138fb"
julia_version = "1.13.0"
os = "macos"

    [[z3.download]]
    sha256 = "fffa9b1b28793595746728d690de567b912632a94e81475d225e9485dd534b28"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7b8780b26cd31eb4a9b4f50ea96209227700a36"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "24569370f9c1bbd3bb5d0aa2600a39358de970999d41526fe2772d698f14e67b"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "390733d3482758048af60effdb1902b0fc47736d"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "4415ffc589162f1af87a5ed50f255374cb4b42eb16f5ffb16f24e200dc935598"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac26c79c7138cd0ffb6f9fdedd82edac05534ba1"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "f49e0167cac0f6609b9ac3b970a9e7d99c8386f00803194887aa9eff7886aca6"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2abef04a9d526bc1805ef34941ad95ffe8d26d3a"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[z3.download]]
    sha256 = "7d3f088c73201eba4b5187e8fec3e02625d29e4a1059ecb807f0a29803648156"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8742276f4a66acb0e7e732c665f4324a6ab1d74e"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[z3.download]]
    sha256 = "e20f9e746283843433eb4f9442fd4a2c7615eb5f1082de8693d7dc1165f63bdc"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-linux-musl-cxx11-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c5745749e8c1ab5b8b2e27d9dff5192a791f3d5"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[z3.download]]
    sha256 = "76b64712c594d1c15ba7b6d6e91da6dc581cac37784b72107cbbc7d375dca88f"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a84e299fa7a380303536bf80d1de4a083b11ebb9"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[z3.download]]
    sha256 = "5592aa1e4bb53ec2dc99cdd717b2225ecd3b236efebd0a751484106ffc9935fc"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25d9188d4195222f1e042a3a0e8e46c2373c4a18"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[z3.download]]
    sha256 = "14de3399bcbbfc985eda91a8fbfd050cd2b8ef59937b0c0f96ea2b84ed65984e"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-linux-musl-cxx11-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "x86_64"
git-tree-sha1 = "88fd5d0277bc061d7fd55f880c4ab52fac2c195f"
julia_version = "1.10.0"
os = "freebsd"

    [[z3.download]]
    sha256 = "1cc0335e2c221546c0d64199b64a2c9ee019a618d193b5b48dbd18ca52aceee1"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "x86_64"
git-tree-sha1 = "ef1b204b1147f6bf81a533a83995a458ba11cba0"
julia_version = "1.11.1"
os = "freebsd"

    [[z3.download]]
    sha256 = "18488019ed3f365edd8d8161a8a283b701382497be270661e963efb3aa65be27"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "x86_64"
git-tree-sha1 = "cf054fa1824045a31ac2d7324351c613534703a5"
julia_version = "1.12.0"
os = "freebsd"

    [[z3.download]]
    sha256 = "180c723c75b24df9e0fff5ed56a6ff3e1778c2d4677bf128a808927ac039c33f"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "x86_64"
git-tree-sha1 = "2f67d276635761fd625f2b0b49d248bb8a4fbc18"
julia_version = "1.13.0"
os = "freebsd"

    [[z3.download]]
    sha256 = "a3cb3338c5b48cda833bf36055be808826294d7a0e9a25a8f053520340e3b8af"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-unknown-freebsd-julia_version+1.13.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99b90656f3bd2e52f48573f64bab6d6570378151"
julia_version = "1.10.0"
os = "windows"

    [[z3.download]]
    sha256 = "f690646043326e873f1a32a1998b60afea06a599655ae36907d8ea273deebb98"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d42357ed26470d35b48b59e07bc4db8f991d980"
julia_version = "1.11.1"
os = "windows"

    [[z3.download]]
    sha256 = "7334d3dcbf9e697b2b7de2a5df48e7aa798d86f3c5f5ae9cd6d71e2ab8d2924c"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9309fdd3e9b788117d933d302ab64482ab0fbda7"
julia_version = "1.12.0"
os = "windows"

    [[z3.download]]
    sha256 = "3276094498e24f0f221ddcb10ae7fdb5e1542b7cd37c5b1cdcb2673ffcb423d0"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[z3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a300f43b534d32a107b8578f8ba016a95e106dd9"
julia_version = "1.13.0"
os = "windows"

    [[z3.download]]
    sha256 = "44dac07246f3859d8489a02ef2f4aae1e4b33d82a06381f69bf709408af0fa64"
    url = "https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases/download/z3-v4.15.4+0/z3.v4.15.4.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
